attention_head_size: 16
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels:
  bearish_atr:
    '0': 0
    '1': 1
  bearish_bollinger:
    '0': 0
    '1': 1
  bearish_macd:
    '0': 0
    '1': 1
  bearish_rsi:
    '0': 0
    '1': 1
  bearish_sma_50_200:
    '0': 0
    '1': 1
  bearish_trend:
    '0': 0
    '1': 1
  bullish_atr:
    '0': 0
    '1': 1
  bullish_bollinger:
    '0': 0
    '1': 1
  bullish_macd:
    '0': 0
    '1': 1
  bullish_rsi:
    '0': 0
    '1': 1
  bullish_sma_50_200:
    '0': 0
    '1': 1
  bullish_trend:
    '0': 0
    '1': 1
  day_of_year:
    '10': 1
    '100': 2
    '101': 3
    '102': 4
    '103': 5
    '104': 6
    '105': 7
    '106': 8
    '107': 9
    '108': 10
    '109': 11
    '11': 12
    '110': 13
    '111': 14
    '112': 15
    '113': 16
    '114': 17
    '115': 18
    '116': 19
    '117': 20
    '118': 21
    '119': 22
    '12': 23
    '120': 24
    '121': 25
    '122': 26
    '123': 27
    '124': 28
    '125': 29
    '126': 30
    '127': 31
    '128': 32
    '129': 33
    '13': 34
    '130': 35
    '131': 36
    '132': 37
    '133': 38
    '134': 39
    '135': 40
    '136': 41
    '137': 42
    '138': 43
    '139': 44
    '14': 45
    '140': 46
    '141': 47
    '142': 48
    '143': 49
    '144': 50
    '145': 51
    '146': 52
    '147': 53
    '148': 54
    '149': 55
    '15': 56
    '150': 57
    '151': 58
    '152': 59
    '153': 60
    '154': 61
    '155': 62
    '156': 63
    '157': 64
    '158': 65
    '159': 66
    '16': 67
    '160': 68
    '161': 69
    '162': 70
    '163': 71
    '164': 72
    '165': 73
    '166': 74
    '167': 75
    '168': 76
    '169': 77
    '17': 78
    '170': 79
    '171': 80
    '172': 81
    '173': 82
    '174': 83
    '175': 84
    '176': 85
    '177': 86
    '178': 87
    '179': 88
    '18': 89
    '180': 90
    '181': 91
    '182': 92
    '183': 93
    '184': 94
    '185': 95
    '186': 96
    '187': 97
    '188': 98
    '189': 99
    '19': 100
    '190': 101
    '191': 102
    '192': 103
    '193': 104
    '194': 105
    '195': 106
    '196': 107
    '197': 108
    '198': 109
    '199': 110
    '2': 111
    '20': 112
    '200': 113
    '201': 114
    '202': 115
    '203': 116
    '204': 117
    '205': 118
    '206': 119
    '207': 120
    '208': 121
    '209': 122
    '21': 123
    '210': 124
    '211': 125
    '212': 126
    '213': 127
    '214': 128
    '215': 129
    '216': 130
    '217': 131
    '218': 132
    '219': 133
    '22': 134
    '220': 135
    '221': 136
    '222': 137
    '223': 138
    '224': 139
    '225': 140
    '226': 141
    '227': 142
    '228': 143
    '229': 144
    '23': 145
    '230': 146
    '231': 147
    '232': 148
    '233': 149
    '234': 150
    '235': 151
    '236': 152
    '237': 153
    '238': 154
    '239': 155
    '24': 156
    '240': 157
    '241': 158
    '242': 159
    '243': 160
    '244': 161
    '245': 162
    '246': 163
    '247': 164
    '248': 165
    '249': 166
    '25': 167
    '250': 168
    '251': 169
    '252': 170
    '253': 171
    '254': 172
    '255': 173
    '256': 174
    '257': 175
    '258': 176
    '259': 177
    '26': 178
    '260': 179
    '261': 180
    '262': 181
    '263': 182
    '264': 183
    '265': 184
    '266': 185
    '267': 186
    '268': 187
    '269': 188
    '27': 189
    '270': 190
    '271': 191
    '272': 192
    '273': 193
    '274': 194
    '275': 195
    '276': 196
    '277': 197
    '278': 198
    '279': 199
    '28': 200
    '280': 201
    '281': 202
    '282': 203
    '283': 204
    '284': 205
    '285': 206
    '286': 207
    '287': 208
    '288': 209
    '289': 210
    '29': 211
    '290': 212
    '291': 213
    '292': 214
    '293': 215
    '294': 216
    '295': 217
    '296': 218
    '297': 219
    '298': 220
    '299': 221
    '3': 222
    '30': 223
    '300': 224
    '301': 225
    '302': 226
    '303': 227
    '304': 228
    '305': 229
    '306': 230
    '307': 231
    '308': 232
    '309': 233
    '31': 234
    '310': 235
    '311': 236
    '312': 237
    '313': 238
    '314': 239
    '315': 240
    '316': 241
    '317': 242
    '318': 243
    '319': 244
    '32': 245
    '320': 246
    '321': 247
    '322': 248
    '323': 249
    '324': 250
    '325': 251
    '326': 252
    '327': 253
    '328': 254
    '329': 255
    '33': 256
    '330': 257
    '331': 258
    '332': 259
    '333': 260
    '334': 261
    '335': 262
    '336': 263
    '337': 264
    '338': 265
    '339': 266
    '34': 267
    '340': 268
    '341': 269
    '342': 270
    '343': 271
    '344': 272
    '345': 273
    '346': 274
    '347': 275
    '348': 276
    '349': 277
    '35': 278
    '350': 279
    '351': 280
    '352': 281
    '353': 282
    '354': 283
    '355': 284
    '356': 285
    '357': 286
    '358': 287
    '359': 288
    '36': 289
    '361': 290
    '362': 291
    '363': 292
    '364': 293
    '365': 294
    '366': 295
    '37': 296
    '38': 297
    '39': 298
    '4': 299
    '40': 300
    '41': 301
    '42': 302
    '43': 303
    '44': 304
    '45': 305
    '46': 306
    '47': 307
    '48': 308
    '49': 309
    '5': 310
    '50': 311
    '51': 312
    '52': 313
    '53': 314
    '54': 315
    '55': 316
    '56': 317
    '57': 318
    '58': 319
    '59': 320
    '6': 321
    '60': 322
    '61': 323
    '62': 324
    '63': 325
    '64': 326
    '65': 327
    '66': 328
    '67': 329
    '68': 330
    '69': 331
    '7': 332
    '70': 333
    '71': 334
    '72': 335
    '73': 336
    '74': 337
    '75': 338
    '76': 339
    '77': 340
    '78': 341
    '79': 342
    '8': 343
    '80': 344
    '81': 345
    '82': 346
    '83': 347
    '84': 348
    '85': 349
    '86': 350
    '87': 351
    '88': 352
    '89': 353
    '9': 354
    '90': 355
    '91': 356
    '92': 357
    '93': 358
    '94': 359
    '95': 360
    '96': 361
    '97': 362
    '98': 363
    '99': 364
    nan: 0
  is_holiday:
    'No': 0
  month:
    April: 1
    August: 2
    December: 3
    February: 4
    January: 5
    July: 6
    June: 7
    March: 8
    May: 9
    November: 10
    October: 11
    September: 12
    nan: 0
  weekday:
    Friday: 1
    Monday: 2
    Thursday: 3
    Tuesday: 4
    Wednesday: 5
    nan: 0
embedding_paddings:
- month
- weekday
- day_of_year
embedding_sizes:
  bearish_atr: !!python/tuple
  - 2
  - 1
  bearish_bollinger: !!python/tuple
  - 2
  - 1
  bearish_macd: !!python/tuple
  - 2
  - 1
  bearish_rsi: !!python/tuple
  - 2
  - 1
  bearish_sma_50_200: !!python/tuple
  - 2
  - 1
  bearish_trend: !!python/tuple
  - 2
  - 1
  bullish_atr: !!python/tuple
  - 2
  - 1
  bullish_bollinger: !!python/tuple
  - 2
  - 1
  bullish_macd: !!python/tuple
  - 2
  - 1
  bullish_rsi: !!python/tuple
  - 2
  - 1
  bullish_sma_50_200: !!python/tuple
  - 2
  - 1
  bullish_trend: !!python/tuple
  - 2
  - 1
  day_of_year: !!python/tuple
  - 365
  - 44
  is_holiday: !!python/tuple
  - 1
  - 1
  month: !!python/tuple
  - 13
  - 7
  weekday: !!python/tuple
  - 6
  - 4
hidden_continuous_size: 128
hidden_continuous_sizes: {}
hidden_size: 8
learning_rate: 0.01
log_gradient_flow: false
log_interval: 64
log_val_interval: null
lstm_layers: 1
max_encoder_length: 100
monotone_constaints: {}
optimizer: Ranger
optimizer_params: null
output_size: 1
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    j4xGndY7pEA=
  max_length: null
  method: standard
  method_kwargs: {}
  scale_: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    mHtCPiwFkEA=
  transformation: relu
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals:
- target_center
- target_scale
time_varying_categoricals_decoder:
- month
- weekday
- day_of_year
- is_holiday
time_varying_categoricals_encoder:
- month
- weekday
- day_of_year
- is_holiday
- bullish_sma_50_200
- bearish_sma_50_200
- bullish_rsi
- bearish_rsi
- bullish_bollinger
- bearish_bollinger
- bullish_macd
- bearish_macd
- bullish_atr
- bearish_atr
- bullish_trend
- bearish_trend
time_varying_reals_decoder:
- Date
- time_idx
- AAII_Bullish
- AAII_Neutral
- AAII_Bearish
- FEDFUNDS
- PIB_USA
- PIB_CHN
- PIB_EMU
- PIB_DEU
- PIB_FRA
- PIB_GBR
- PIB_JPN
- PIB_IND
- PIB_BRA
- PIB_CAN
- PIB_AUS
- PIB_ITA
- PIB_KOR
- PIB_MEX
- PIB_IDN
- PIB_SAU
- PIB_ZAF
- PIB_TUR
- PIB_ESP
- relative_time_idx
time_varying_reals_encoder:
- Date
- time_idx
- AAII_Bullish
- AAII_Neutral
- AAII_Bearish
- FEDFUNDS
- PIB_USA
- PIB_CHN
- PIB_EMU
- PIB_DEU
- PIB_FRA
- PIB_GBR
- PIB_JPN
- PIB_IND
- PIB_BRA
- PIB_CAN
- PIB_AUS
- PIB_ITA
- PIB_KOR
- PIB_MEX
- PIB_IDN
- PIB_SAU
- PIB_ZAF
- PIB_TUR
- PIB_ESP
- relative_time_idx
- target
- open
- max
- min
- var
- target_lag1
- target_lag2
- target_lag3
- target_lag4
- target_lag5
- SMA_5
- EMA_5
- SMA_10
- EMA_10
- SMA_20
- EMA_20
- Bollinger_Upper_20
- Bollinger_Lower_20
- MACD
- Signal_Line
- CCI_10
- CCI_20
- ROC_10
- ROC_14
- ROC_20
- Stochastic_14_K
- Stochastic_14_D
- Williams_%R_14
- VIX
- EUVIX
- target_eustoxx
- target_ibex35
- target_nasdaq
weight_decay: 0.0
x_categoricals:
- month
- weekday
- day_of_year
- is_holiday
- bullish_sma_50_200
- bearish_sma_50_200
- bullish_rsi
- bearish_rsi
- bullish_bollinger
- bearish_bollinger
- bullish_macd
- bearish_macd
- bullish_atr
- bearish_atr
- bullish_trend
- bearish_trend
x_reals:
- target_center
- target_scale
- Date
- time_idx
- AAII_Bullish
- AAII_Neutral
- AAII_Bearish
- FEDFUNDS
- PIB_USA
- PIB_CHN
- PIB_EMU
- PIB_DEU
- PIB_FRA
- PIB_GBR
- PIB_JPN
- PIB_IND
- PIB_BRA
- PIB_CAN
- PIB_AUS
- PIB_ITA
- PIB_KOR
- PIB_MEX
- PIB_IDN
- PIB_SAU
- PIB_ZAF
- PIB_TUR
- PIB_ESP
- relative_time_idx
- target
- open
- max
- min
- var
- target_lag1
- target_lag2
- target_lag3
- target_lag4
- target_lag5
- SMA_5
- EMA_5
- SMA_10
- EMA_10
- SMA_20
- EMA_20
- Bollinger_Upper_20
- Bollinger_Lower_20
- MACD
- Signal_Line
- CCI_10
- CCI_20
- ROC_10
- ROC_14
- ROC_20
- Stochastic_14_K
- Stochastic_14_D
- Williams_%R_14
- VIX
- EUVIX
- target_eustoxx
- target_ibex35
- target_nasdaq
